src/dbt_osmosis/core/osmosis.py
DbtYamlManager.yaml_handler assumed that if a schema.yml file existed, it contained data. This caused a `NoneType is not iterable` exception when 1) reading an empty file, then 2) checking it for a key.
=> Handle updating empty schema.yml files

src/dbt_osmosis/main.py
**Problem**
Sometimes when running `server serve --register-project` the project didn't get registered and server gets stuck.
**Solution**
The register project thread is sending the post request to the server probably while the server is still doing some initialization, and can't process the request properly.
Changing the order fixes the issue, but not the most robust solution.
**Recommendation**
Server's `register` endpoint should be improved to avoid this issue.
=> [bugfix] Trigger register project thread after flask server was started.

src/dbt_osmosis/main.py
It's easy to make a mistake and install `sqlfluff-templater-dbt` in the same virtualenv as `dbt-osmosis`. This doesn't work, so check for this at server startup and fail if it's present.
=> Raise an error at server startup if sqlfluff-templater-dbt is installed

src/dbt_osmosis/core/osmosis.py
This small extension to the `DbtProjectContainer.add_project()` function permits callers to specify `vars` for `ConfigInterface`. This is a step towards rewriting `sqlfluff-templater-dbt` to use `dbt-osmosis` rather than calling dbt directly.
=> Allow passing variable definitions to add_project()

.gitignore, src/dbt_osmosis/core/osmosis.py
This PR updates the get_columns method to account for the fact that in BigQuery Projects, the columns can be nested structures. This is accounted for by flattening these structs to ensure that every name is accounted for. This logic will be used when the type returned by the adapter is a BigQuery Column with the flatten method. Otherwise, the column names will be returned without flattening.
Fixes #32
=> Allow for documenting Struct Fields - BigQuery

src/dbt_osmosis/core/osmosis.py
@z3z1ma With the following change, `SchemaFileOrganizationPattern` is no longer referenced anywhere (Investigated by `git grep`). Therefore, remove the `SchemaFileOrganizationPattern` by this pull request.
- https://github.com/z3z1ma/dbt-osmosis/commit/703fe300c8f83bbba29983307d4caf4d08d7e351
- https://github.com/z3z1ma/dbt-osmosis/commit/4717ebd427cf434b041f1316c79d5aaa93cf0a55
=> [nit] remove SchemaFileOrganizationPattern

docs/docs/tutorial-basics/commands.md
The option `project-path` does not exist, so I rename it to `project-dir`.
=> fixed server sub-command option's name

src/dbt_osmosis/core/osmosis.py, src/dbt_osmosis/main.py
Fixes #57 
First shot at adding support for providing a catalog file as input.
Things that you might want me to change:
- using `col.lower()` - I had to use it to make the code work with my own project on Snowflake where the YML files are defined with lowercase columns but are stored as uppercase in `catalog.json`
- the parameter name called `--catalog-file` or how we want users to be able to pick between offline (catalog) vs online (connecting to the warehouse)
- how I handle `parts` to match the function parameter and catalog file
=> Allow reading from catalog for document

README.md
Update the README to include quotes in the invocation of `pip install "dbt-osmosis[workbench]"`
=> Add quotes to pip install "dbt-osmosis[workbench]"

src/dbt_osmosis/core/osmosis.py
Fix #58.
When upstream column name is written lowercase in yaml file, prior_knowledge cannot get each items and return empty dictionary.
This is because the column names in catalog.json are uppercase in Snowflake.
=> fixed upstream knowledge in case the key is lower case

docs/docs/tutorial-yaml/configuration.md
Hi all,
the `dbt-osmosis` block was missing in the source examples, this pull request fixes that.
```
vars:
dbt-osmosis:                              # <- was missing
salesforce:
path: "staging/salesforce/source.yml"
schema: "salesforce_v2"
```
Cheers!
=> fix a bug in the example code for source definitions

src/dbt_osmosis/core/osmosis.py
I'm using dbt-osmosis to maintain the metadata for BigQuery, especially for column description. We can write column description with nested fields like
```yaml
version: 2
models:
- name: example_table
columns:
- name: root_column
description: "Description of root_column"
- name: root_column.sub1
description: "Description of root_column.sub1"
- name: root_column.sub2
description: "Description of root_column.sub2"
```
After running `dbt-osmosis yaml refactor models/example_table`, the information of the root level column disappeared 😭 .
```yaml
version: 2
models:
- name: example_table
columns:
- name: root_column.sub1
description: "Description of root_column.sub1"
- name: root_column.sub2
description: "Description of root_column.sub2"
```
Data users need the description of the root column. …
=> Allow to keep root level column name that contains nested fields

src/dbt_osmosis/core/osmosis.py, src/dbt_osmosis/main.py
dbt-osmosis inherits not only column descriptions but also (adding) tags and (merging) meta. Sometimes we only want to inherit column descriptions. So I added options `--skip-add-tags` and `--skip-merge-meta`.
=> Add options for `--skip-add-tags` and `--skip-merge-meta`

src/dbt_osmosis/core/osmosis.py
Partially resolve https://github.com/z3z1ma/dbt-osmosis/issues/66 FYI @awoehrl.
We often rename column names from camelCase to snake_case and it would be really helpful if dbt-osmosis could inherit column renaming like this
```sql
SELECT
priceType AS price_type,
countryName AS country_name,
...
FROM
table_name
```
=> Fuzzy matching on column name (from CamelCase to snake_case)

docs/docs/tutorial-yaml/configuration.md, src/dbt_osmosis/core/osmosis.py
1. For multi-database warehouses (like snowflake) it's important to be able to specify which database a set of sources resides in as well as a schema.
2. Right now the `yaml refactor` command fails when source config vars are dictionaries instead of just a path:
```yml
vars:
dbt-osmosis:
<source_name>: <path>  # Works
<source_name>:  # Causes failures
path: <path>
schema: <schema>
```
1. Parse a database from the source spec, still defaulting to the configured default database from the dbt profile.
2. Write the database to generated source yml files explicitly.
3. Update documentation.
Add conditional logic to handle source specs that are dictionaries.
=> Database specification for source bootstrapping+fix

docs/docs/intro.md
I noticed that the minimum Python version mentioned in the documentation has not been updated. It is updated by https://github.com/z3z1ma/dbt-osmosis/commit/e59809093ba1710a3c878ba53473495969545994.
=> [nit] Upgrade the minimum Python version to 3.8 in docs

src/dbt_osmosis/vendored/dbt_core_interface/project.py
=> Fix to load dbt vars using `yaml` instead of `json`

.pre-commit-config.yaml, src/dbt_osmosis/main.py, src/dbt_osmosis/vendored/dbt_core_interface/project.py, tests/test_column_level_knowledge_propagator.py, tests/test_osmosis.py
It would be good to implement hooks to check the coding style in python using `pre-commit`.
=> Enable the pre-commit hooks to check the coding style in python

src/dbt_osmosis/core/osmosis.py
Issue description:
- When running `refactor` on sources, in case if source name is not the same as identifier - we should use identifier, if available.
=> Add identifier property support for source entity type.

src/dbt_osmosis/core/osmosis.py
dbt does not officially support column comments in Column class.
Therefore, the column description in sources of schema.yml generated from database information is always empty.
However, if a database adapter supports column comments, we will give you the ability to add column comments.
I will work to get `dbt-core` to support this feature.
It would be great if dbt-osmosis would automatically fetch comments from the database when we add a source name to schema.yml.
What do you think about this?
=> feat: load column description from db.

src/dbt_osmosis/core/osmosis.py
**Issue description:**
When running `refactor`, process any changes to source yaml only when it exists/is defined. It is quite common for intermediate and mart models to not have a source file defined.
**How to reproduce**
Run `refactor` on a folder that contains schema yaml file but doesn't contain the source yaml file
**Additional context**
Should fix #115
=> [Fix] Process sources only when source yaml is available

src/dbt_osmosis/core/osmosis.py
Currently, `dbt-osmosis` uses the data_type and comment of the parent column for all of its children. This PR fix that.
=> Get the data_type and comment of child column instead of its parent

src/dbt_osmosis/core/osmosis.py
I have a somewhat large project that I'm trying to refactor. When I was running dbt-osmosis, I was getting this error randomly:
```
ERROR    Failed to draft project structure update plan for model.my_project.some_model: 'models'         osmosis.py:610
```
The error message isn't very helpful. This same error would be reported for many different models, while other models would succeed during this step.
Running dbt-osmosis for a **single model** at a time produced no such error -- even on models that were erroring when dbt-osmosis was invoked across many models.
Looking at the traceback a better picture
```
ERROR    Failed to draft project structure update plan for model.my_project.some_model: 'models'         osmosis.py:610
╭───────────────────────────────────────────── Traceback (most …
```
=> Fix race condition in draft phase

src/dbt_osmosis/core/osmosis.py
CI has failed since the merge of https://github.com/z3z1ma/dbt-osmosis/pull/131.
- https://github.com/z3z1ma/dbt-osmosis/actions/runs/8043780107/job/22102412580
The error was related to `trailing-whitespace` and has been fixed.
=> Fix pre-commit error by removing trailing whitespace

src/dbt_osmosis/core/osmosis.py
fixes https://github.com/z3z1ma/dbt-osmosis/issues/135. FYI @b-per @z3z1ma 
I fixed `n_cols_added` was not initialized when the `--skip-add-columns` option was specified.
=> Initialize the variable `n_cols_added`

.pre-commit-config.yaml
Since the `.pre-commit-config.yaml` contained two `hadolint/hadolint` configurations, we removed the duplicates.
=> nit: Remove duplication setting for hadolint-docker

.github/workflows/labeler.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/tests.yml
I've updated `actions/checkout` and `actions/setup-python` to the latest versions. Because both are actions that use Node.js 16 and [GitHub has recommended](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) that we move to actions that use Node.js 20.
- https://github.com/z3z1ma/dbt-osmosis/actions/runs/8542607513
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
By the way, it is hard for humans to update the versions of libraries and actions, so it might be a good idea to introduce renovate and dependabot for dbt-osmosis as well :)
=> nit: Update actions/checkout and actions/setup-python

src/dbt_osmosis/core/osmosis.py
@z3z1ma After updating dbt-osmosis to [version 0.12.8](https://github.com/z3z1ma/dbt-osmosis/blob/main/CHANGELOG.md#0128---2024-03-29), I noticed that the `data_type` attribute disappears from within the yaml. After reading the source code, I noticed that the `skip_add_data_types` condition in the `update_columns_data_type` function is wrong, so I will fix it.
- ref: https://github.com/z3z1ma/dbt-osmosis/commit/7756a80c0f449946c6d31584d51babe6f0802292
=> Fix `skip_add_data_types` condition in `update_columns_data_type`

src/dbt_osmosis/core/column_level_knowledge_propagator.py, src/dbt_osmosis/core/osmosis.py, src/dbt_osmosis/main.py, tests/test_column_level_knowledge_propagator.py
I utilize BigQuery's column-level access control by setting policy_tags in numerous model.yml and source.yml files within dbt.
It would be beneficial if I could inherit policy_tags.
To this end, I have introduced a feature that allows not only the inheritance of policy_tags but also specified keys.
=> [feature] add inheritance for specified keys

.github/workflows/tests.yml
dbt-osmosis currently supports working with various dbt-cores (we are assuming [1.3 or higher](https://github.com/z3z1ma/dbt-osmosis/blob/a1c21093c06713fb5f5486a3e3257c7ac5153857/src/dbt_osmosis/vendored/dbt_core_interface/project.py#L97-L137), I believe).
However, I think it is possible that dbt-osmosis will not work in the future if there is a change in the spec from a particular dbt-core version, as in https://github.com/z3z1ma/dbt-osmosis/issues/139. We have already received a pull request at https://github.com/z3z1ma/dbt-osmosis/pull/149 to support the change to dbt 1.8. We would like to ensure through CI that this change will not break existing behavior even if dbt is up to version 1.7.
Therefore, I have made a modification to make sure that CI will work with multiple dbt-core …
=> Modify to test with multiple versions of dbt-core

pyproject.toml, src/dbt_osmosis/vendored/dbt_core_interface/project.py
Currently, dbt-osmosis supports a very wide range of dbt-core versions. As a result, there is code that diverges depending on the version of dbt-core, resulting in complexity and test case omissions. And `Support level and end date` for dbt 1.5 and below is `End of Life`.
- ref: https://docs.getdbt.com/docs/dbt-versions/core
This pull request explicitly limits the supported dbt-core versions so that dbt-osmosis can keep up with new dbt-core versions as they become available and remain highly maintainable.
- ref: https://github.com/z3z1ma/dbt-osmosis/pull/150/files#r1600410662
=> Modify to support dbt-core 1.6 and above

src/dbt_osmosis/vendored/dbt_core_interface/project.py
`dbt_core v1.8.0` introduces dependency on `dbt_common` package which wasn't the thing prior to 1.8.x.
In `dbt_common`, they introduce [`InvocationContext` class](https://github.com/dbt-labs/dbt-common/pull/52/files).
It's used in cli's `preflight` decorator that sets the context before any actual CLI operation:
- [set_invocation_context](https://github.com/dbt-labs/dbt-core/blob/v1.8.0/core/dbt/cli/requires.py#L58)
- [get_invocation_context](https://github.com/dbt-labs/dbt-core/blob/v1.8.0/core/dbt/cli/requires.py#L65)
Then it's used in `dbt_core`'s [`SecretContext`](https://github.com/dbt-labs/dbt-core/blob/v1.8.0/core/dbt/context/secret.py#L32) which is necessary if you use something like:
This PR tries to import `set_invocation_context` and `get_env` from `dbt_common` and then set ENV …
=> Fix: set ENV VARS as invocation context for dbt >= 1.8

src/dbt_osmosis/core/osmosis.py
Hello! I am using your library for my work and have a feature request, so I've submitted a pull request. I would be grateful if you could take a look.
- Ensures that when specifying a `--catalog-file` argument with `catalog.json`, the descriptions in the model's YAML file are populated from `catalog.json`.
- When using the --catalog-file argument with `catalog.json`, descriptions from `catalog.json `are only populated in the model’s YAML file if it already exists and lacks a column key.
If the model’s YAML file does not exist, the descriptions from `catalog.json` are **not populated**.
- When specifying the `--catalog-file` argument, if the model’s YAML file does not exist and is newly created, descriptions from `catalog.json` will be populated.
- When using the `--catalog-file` argument, …
=> Overwrite description when --catalog-file is specified

demo_duckdb/models/schema.yml, demo_duckdb/models/staging/schema.yml, src/dbt_osmosis/core/column_level_knowledge_propagator.py, tests/test_column_level_knowledge_propagator.py
Resolves: https://github.com/z3z1ma/dbt-osmosis/issues/66 (partially addressed in https://github.com/z3z1ma/dbt-osmosis/pull/79, but the issue with fuzzy matching using prefixes remains).
- Inspired by https://github.com/z3z1ma/dbt-osmosis/pull/79#issuecomment-1674201896, I added a feature to the `update_undocumented_columns_with_prior_knowledge` method which checks for `osmosis-prefix` metadata in a column’s original knowledge
- If an `osmosis-prefix` is provided, osmosis will remove the prefix from the column name and search for prior knowledge using the modified column name
- Added unit tests for the `update_undocumented_columns_with_prior_knowledge` method to validate its behavior when `osmosis-prefix` metadata is specified in the model’s `schema.yml`
=> Fuzzy matching on prefix provided by metadata

src/dbt_osmosis/core/osmosis.py
Hi maintainers, this is my first contribution, so if there are any guidelines or best practices I should follow, please let me know 😄 
Since dbt-osmosis v1.x.x, the method for generating the `CatalogKey` has changed. In the current implementation, when `adapter.get_relation` is called for a dbt model that uses an `alias`, `None` is returned.
Until v0.14.0, if an alias was used, the alias would take priority, and that behavior was correct.
(ref. https://github.com/z3z1ma/dbt-osmosis/blob/v0.14.0/src/dbt_osmosis/core/osmosis.py#L324-L328)
So, I have modified it so that if it is neither a BaseRelation nor a NodeType.Source, the alias is used.
---
```
$ cat <<EOF > demo_duckdb/models/jaffle_shop/main/sample_alias.yml
---
version: 2
models:
- name: sample_alias
columns:
- name: order_id …
```
=> Fix: Fix 'No relation found' error for models using alias

src/dbt_osmosis/core/osmosis.py
In _is_file_match(), the condition model_or_dir.samefile(yaml_path) raises an issue FileNotFoundError with yamlPath.
This is a simple check to ensure the yaml file exists.
How to reproduce : 
Have seeds from external packages such as [dbt_project_evaluator_exceptions.csv](https://dbt-labs.github.io/dbt-project-evaluator/latest/customization/exceptions/#1-create-a-new-seed). 
Patch path will be dbt_project_evaluator://seeds/seeds.yml even though it does not exist in the project.
=> fix FileNotFoundError with external packages

src/dbt_osmosis/cli/main.py, src/dbt_osmosis/core/osmosis.py
Running dbt-osmosis on python 3.9 results in the following error : 
`AttributeError: module 'typing' has no attribute 'ParamSpec'`
Also switching to typing.Union in osmosis.py, it was throwing : 
```
python3.9/site-packages/dbt_osmosis/core/osmosis.py", line 1096, in _get_yaml_path_template
path_template = _find_first(t.cast(list[str | None], conf), lambda v: v is not None)
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
I tested the refactor command and it works fine after those modifications
=> fix python version check for typing import

.gitignore, .vscode/settings.json, src/dbt_osmosis/core/osmosis.py
Adding support for injecting metadata from other manifests as defined in dbt-loom so that Inherit Upstream Column Knowledge can retrieve data from other projects.
If dbt-loom is installed, dbt-loom gets used to pull the relevant manifests as defined there.
Then the model nodes that are visible are injected into the manifest.
The Inherit Upstream Column Knowledge portion is modified to allow the f() function to search primarily through fqn to find these nodes, as they are from a different project, and that is okay here.
The code works, it retrieves column level metadata from one project to another.
But it should be rewritten to better conform to the overall logic and to be better.
=> Add support for inheriting metadata through dbt-loom configured cross project dependencies

src/dbt_osmosis/core/osmosis.py
In dbt-osmosis, the ruamel-yaml library being used treats strings that look like Booleans as strings rather than as Booleans.
* https://github.com/commx/ruamel-yaml/blob/280677cf647912c599d8886000020d6ffbbb4216/_doc/detail.ryd#L178
* https://github.com/commx/ruamel-yaml/blob/280677cf647912c599d8886000020d6ffbbb4216/resolver.py#L26-L35
On the other hand, dbt is implemented under the assumption that strings resembling Booleans are treated as Booleans, and if one wishes to treat them as strings, quoting is required.
* https://github.com/dbt-labs/dbt-core/blob/9d7820c356e6bbdd8af756df1fc1b1a2c086b857/tests/unit/clients/test_jinja.py#L285-L295
In the current implementation of dbt-osmosis, strings that resemble Booleans are output as strings without quotes. As a result, when the output from …
=> fix: quoted boolean-like string must be dumped with quotes

src/dbt_osmosis/core/osmosis.py
In data warehouses like Snowflake, where all identifiers are automatically converted to uppercase unless special handling is applied, running dbt-osmosis with the `--output-to-lower` option previously resulted in only the source name remaining in uppercase when creating missing sources. This pull request changes the behavior so that the `--output-to-lower` option is respected for the source name as well.
```yaml
vars:
dbt-osmosis:
sources:
snowflake__account_usage:
path: "landing/snowflake/account_usage/sources.yml"
database: snowflake
schema: account_usage
```
You can see that only the source name ACCESS_HISTORY is in uppercase.
```yaml
version: 2
sources:
- name: snowflake__account_usage
database: snowflake
schema: account_usage
tables:
- name: ACCESS_HISTORY
description: ''
columns:
- …
```
=> fix: Respect output-to-lower option for name of sources

src/dbt_osmosis/core/osmosis.py
Hi @z3z1ma,
I’ve fixed a bug in this pull request that occurs when using Snowflake as the dbt adapter and running dbt-osmosis with the `--output-to-lower` option: even if you drop a column in Snowflake, dbt-osmosis doesn’t remove it from your schema file.
When Snowflake is used, dbt-osmosis uppercases column names via the `normalized_column_name()` method. However, if you specify `--output-to-lower`, the names in `node.columns` remain lowercase. As a result, in the original `remove_columns_not_in_database()` implementation, the final `node.columns.pop` step never matches anything, so dropped columns aren’t removed from the schema file.
I considered adding a reproducible case, but since this only happens with Snowflake, I hope the above explanation and the implementation changes are …
=> fix: Use original node.columns keys to pop from node.columns when removing columns from schema files

src/dbt_osmosis/core/osmosis.py
Hi @z3z1ma,
In the current dbt-osmosis implementation, `_maybe_use_precise_dtype(...)` is called without a `ResultNode`. As a result, the `numeric-precision-and-scale` and `string-length` options always fall back to their defaults, so configurations like:
```
models:
jaffle_shop_duckdb:
+dbt-osmosis: "{node.database}/{node.schema}/{node.name}.yml"
+dbt-osmosis-options:
numeric-precision-and-scale: true
string-length: true
```
are ignored.
To fix this, I updated the code so that if `get_columns(...)` is passed a `ResultNode`, it also forwards that `ResultNode` to `_maybe_use_precise_dtype(...)`.
---
```
$ echo "${PWD/#$HOME/~}"
~/src/github.com/civitaspo/dbt-osmosis
$ vim ./demo_duckdb/dbt_project.yml
$ GIT_PAGER=cat git diff ./demo_duckdb/dbt_project.yml
diff --git …
```
=> fix: Respect `numeric-precision-and-scale` and `string-length` options in node settings
